### ISSUE TITLE
Makes page not mobile-friendly; can scroll horizontally on mobile

### ISSUE THREAD

**Issue by ghost** [sukiwp/columns-alignment-fix-for-elementor#1]
I truly appreciate your work on the plugin! Unfortunately, it is not fully responsive. It makes the screen wider than the mobile device. This causes horizontal scroll and is not mobile-friendly.

When I view my page on a mobile device (I've only tested iOS), the page overflows the screen so I can drag the page left and right and it will scroll horizontally.

With the fix disabled, the page does not overflow and I cannot drag the page left or right and it does not scroll horizontally (harder to show with video).

**Comment by daviedR** [comment]
Can you share the page URL? It would be easier to look into the issue if I can test it myself.

**Comment by kelseyclubb** [comment]
https://bettertravelmemories.com/best-sony-a6500-lenses/#top-3

**Comment by kelseyclubb** [comment]
I just added the following code to my custom CSS and it seems to have fixed the problem (I no longer have horizontal scroll):

`.elementor-columns-alignment-fix-enabled {
	overflow: hidden;
}`

Not sure if this is something you can and/or want to add to the plugin, but for now this will be my way to make it mobile-friendly.

**Comment by daviedR** [comment]
The `overflow: hidden` is not a best solution, because any `box-shadow` would be cut.

I have tested and couldn't replicate the issue on my content. I need to see the issue online to be able to detect what causing the horizontal scroll.

**Comment by kelseyclubb** [comment]
Okay, here is the section that overflows on mobile:

https://bettertravelmemories.com/best-sony-a6500-lenses/#top-3

**Comment by daviedR** [comment]
You are right, I will find a solution for this. 

But my suggestion is to add `overflow-x: hidden` in the `body` or `#page` tag (I see you are using Astra).
